// Mock data — 用于无 API 时的本地演示
// 一期 PRD 要求后端实现 /api/dashboard/map，本文件先支持本地原型

import type { MemoryNodeData, RelationData, MapStats, GrowthData } from './types';

export const MOCK_NODES: MemoryNodeData[] = [
  {
    id: 'r1',
    title: 'camelCase 命名',
    content: '本项目使用 camelCase 命名变量、函数、文件名。不用 snake_case。',
    category: 'code',
    status: 'active',
    confidence: 0.95,
    version: 3,
    tags: ['typescript', 'naming', 'style'],
    trigger_context: '编写函数/变量/文件命名',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code', 'Cursor'],
    hit_count: 312,
    created_at: '2026-03-15',
    updated_at: '2026-05-28',
    source_snippet: '「不要用 snake_case，这个项目统一用 camelCase，包括文件名也是」',
  },
  {
    id: 'r2',
    title: 'TypeScript strict 模式',
    content: 'tsconfig 必须开启 strict: true，禁止关闭 any 隐式检查。',
    category: 'code',
    status: 'active',
    confidence: 0.92,
    version: 2,
    tags: ['typescript', 'config', 'style'],
    trigger_context: '配置 tsconfig / 添加新依赖',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code'],
    hit_count: 88,
    created_at: '2026-03-20',
    updated_at: '2026-04-15',
    source_snippet: '「把 strict 开起来，别再用 any 偷懒」',
  },
  {
    id: 'r3',
    title: 'ESLint 规范',
    content: '使用项目自带的 ESLint config，不允许关闭规则。',
    category: 'code',
    status: 'active',
    confidence: 0.88,
    version: 1,
    tags: ['typescript', 'lint', 'style'],
    trigger_context: '提交代码 / 配置编辑器',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code', 'Cursor', 'Codex'],
    hit_count: 64,
    created_at: '2026-04-02',
    updated_at: '2026-04-02',
  },
  {
    id: 'r4',
    title: 'Result 类型错误处理',
    content: '错误处理优先用 Result<T, E> 类型，不直接 throw。',
    category: 'architecture',
    status: 'active',
    confidence: 0.88,
    version: 2,
    tags: ['typescript', 'error-handling', 'pattern'],
    trigger_context: '编写 service / 处理边界条件',
    project_path: '/Users/dev/api-server',
    agents: ['Claude Code'],
    hit_count: 145,
    created_at: '2026-02-10',
    updated_at: '2026-05-01',
    source_snippet: '「不要 throw，统一用 Result 包一下」',
  },
  {
    id: 'r5',
    title: 'DDD 分层架构',
    content: '代码按 domain / application / infrastructure 三层组织。',
    category: 'architecture',
    status: 'active',
    confidence: 0.85,
    version: 4,
    tags: ['architecture', 'pattern', 'ddd'],
    trigger_context: '新建模块 / 重构目录',
    project_path: '/Users/dev/api-server',
    agents: ['Claude Code', 'Cursor'],
    hit_count: 56,
    created_at: '2026-01-20',
    updated_at: '2026-05-10',
  },
  {
    id: 'r6',
    title: '事件溯源',
    content: '核心领域模型用 Event Sourcing，状态从事件流重建。',
    category: 'architecture',
    status: 'other',
    confidence: 0.72,
    version: 1,
    tags: ['architecture', 'pattern', 'event'],
    trigger_context: '设计新的领域对象',
    project_path: '/Users/dev/api-server',
    agents: ['Cursor'],
    hit_count: 12,
    created_at: '2026-05-15',
    updated_at: '2026-05-15',
  },
  {
    id: 'r7',
    title: 'vitest 单元测试',
    content: '测试统一用 vitest，不引入 jest。',
    category: 'practice',
    status: 'active',
    confidence: 0.92,
    version: 1,
    tags: ['testing', 'tooling'],
    trigger_context: '添加测试 / 配置 CI',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code', 'Cursor'],
    hit_count: 78,
    created_at: '2026-03-25',
    updated_at: '2026-03-25',
  },
  {
    id: 'r8',
    title: 'pnpm 包管理',
    content: '本项目使用 pnpm，不要用 npm/yarn。',
    category: 'practice',
    status: 'active',
    confidence: 0.95,
    version: 2,
    tags: ['tooling', 'package-manager'],
    trigger_context: '安装依赖 / 生成脚本 / lockfile',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code', 'Cursor', 'Codex'],
    hit_count: 312,
    created_at: '2026-02-01',
    updated_at: '2026-04-20',
    source_snippet: '「别用 npm，这项目用 pnpm」',
  },
  {
    id: 'r9',
    title: 'Conventional Commits',
    content: '提交信息遵循 Conventional Commits 规范。',
    category: 'practice',
    status: 'active',
    confidence: 0.90,
    version: 1,
    tags: ['git', 'commit', 'style'],
    trigger_context: 'git commit',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code'],
    hit_count: 88,
    created_at: '2026-03-30',
    updated_at: '2026-03-30',
  },
  {
    id: 'r10',
    title: 'pre-commit hook',
    content: '所有 commit 必须通过 pre-commit hook 检查。',
    category: 'practice',
    status: 'active',
    confidence: 0.86,
    version: 1,
    tags: ['git', 'tooling'],
    trigger_context: 'git commit / 配置项目',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code'],
    hit_count: 45,
    created_at: '2026-04-10',
    updated_at: '2026-04-10',
  },
  {
    id: 'r11',
    title: '冲突：fetch 位置',
    content: '业务组件不应该直接 fetch，应该通过 service 层。',
    category: 'architecture',
    status: 'conflicted',
    confidence: 0.78,
    version: 1,
    tags: ['architecture', 'pattern', 'fetch'],
    trigger_context: '在组件中调用 API',
    project_path: '/Users/dev/web-app',
    agents: ['Claude Code', 'Cursor'],
    hit_count: 23,
    created_at: '2026-05-01',
    updated_at: '2026-05-22',
  },
  {
    id: 'r12',
    title: 'React Server Components',
    content: '默认用 RSC，client component 显式声明。',
    category: 'architecture',
    status: 'other',
    confidence: 0.70,
    version: 1,
    tags: ['react', 'pattern'],
    trigger_context: '新建页面 / 组件',
    project_path: '/Users/dev/web-app',
    agents: ['Cursor'],
    hit_count: 18,
    created_at: '2026-05-20',
    updated_at: '2026-05-20',
  },
  {
    id: 'r13',
    title: '禁止 any 类型',
    content: 'TypeScript 中禁止使用 any，必要时用 unknown 替代。',
    category: 'code',
    status: 'active',
    confidence: 0.91,
    version: 2,
    tags: ['typescript', 'style'],
    trigger_context: '类型定义 / 修复类型错误',
    project_path: '/Users/dev/my-app',
    agents: ['Claude Code', 'Codex'],
    hit_count: 124,
    created_at: '2026-03-18',
    updated_at: '2026-05-05',
  },
  {
    id: 'r14',
    title: 'API 路径前缀',
    content: 'REST API 统一 /api/v1/ 前缀，禁止散落。',
    category: 'architecture',
    status: 'active',
    confidence: 0.84,
    version: 1,
    tags: ['api', 'pattern'],
    trigger_context: '新建 endpoint',
    project_path: '/Users/dev/api-server',
    agents: ['Claude Code'],
    hit_count: 34,
    created_at: '2026-04-15',
    updated_at: '2026-04-15',
  },
  {
    id: 'r15',
    title: '日志用 pino',
    content: 'Node 服务统一用 pino 记录结构化日志。',
    category: 'practice',
    status: 'active',
    confidence: 0.82,
    version: 1,
    tags: ['tooling', 'logging'],
    trigger_context: '添加日志 / 排查问题',
    project_path: '/Users/dev/api-server',
    agents: ['Claude Code'],
    hit_count: 28,
    created_at: '2026-04-22',
    updated_at: '2026-04-22',
  },
];

// 关联关系（手工标注，模拟后端 edgeScore + tier 分类结果）
// tier = signal（冲突/进化，永远显示）/ structure（强关联，默认 top-3）/ whisper（弱关联，按需）
// score 用于 tier 内排序（前端 top-N）
export const MOCK_RELATIONS: Array<{ source: string; target: string; data: RelationData }> = [
  // === signal: 冲突（永远显示，红色脉冲）===
  { source: 'r11', target: 'r12', data: { tier: 'signal', signalType: 'conflict', score: 1.0, reason: '冲突：同项目矛盾规则' } },

  // === structure: 强关联（同项目 + 多共享标签，默认可见）===
  { source: 'r1', target: 'r2', data: { tier: 'structure', score: 0.85, reason: 'same project · my-app' } },
  { source: 'r1', target: 'r3', data: { tier: 'structure', score: 0.82, reason: 'same project · my-app' } },
  { source: 'r1', target: 'r13', data: { tier: 'structure', score: 0.88, reason: 'same project · shared 2 tag(s)' } },
  { source: 'r2', target: 'r3', data: { tier: 'structure', score: 0.80, reason: 'same project · shared 2 tag(s)' } },
  { source: 'r2', target: 'r13', data: { tier: 'structure', score: 0.84, reason: 'same project · shared 2 tag(s)' } },
  { source: 'r7', target: 'r8', data: { tier: 'structure', score: 0.78, reason: 'same project · my-app' } },
  { source: 'r7', target: 'r9', data: { tier: 'structure', score: 0.72, reason: 'same project · my-app' } },
  { source: 'r8', target: 'r10', data: { tier: 'structure', score: 0.75, reason: 'same project · shared 1 tag(s)' } },
  { source: 'r9', target: 'r10', data: { tier: 'structure', score: 0.74, reason: 'same project · shared 1 tag(s)' } },
  { source: 'r4', target: 'r5', data: { tier: 'structure', score: 0.83, reason: 'same project · shared 2 tag(s)' } },
  { source: 'r4', target: 'r14', data: { tier: 'structure', score: 0.76, reason: 'same project · api-server' } },
  { source: 'r5', target: 'r14', data: { tier: 'structure', score: 0.74, reason: 'same project · api-server' } },

  // === whisper: 弱关联（单共享标签 / 语义相似，按需显示）===
  { source: 'r4', target: 'r6', data: { tier: 'whisper', score: 0.32, reason: 'shared 1 tag(s): #pattern' } },
  { source: 'r8', target: 'r15', data: { tier: 'whisper', score: 0.28, reason: 'shared 1 tag(s): #tooling' } },
  { source: 'r11', target: 'r4', data: { tier: 'whisper', score: 0.26, reason: 'shared 1 tag(s): #pattern' } },
  { source: 'r1', target: 'r7', data: { tier: 'whisper', score: 0.22, reason: '语义相似：项目规范' } },
  { source: 'r4', target: 'r12', data: { tier: 'whisper', score: 0.20, reason: '语义相似：模式选择' } },
  { source: 'r6', target: 'r12', data: { tier: 'whisper', score: 0.18, reason: '语义相似：状态管理' } },
];

const ACHIEVEMENTS = [
  { id: 'first', label: '第一条记忆', icon: '🌱', unlocked: true },
  { id: 'multi-agent', label: '跨 Agent', icon: '🔗', unlocked: true },
  { id: 'ten-active', label: '10 条 Active', icon: '✅', unlocked: true },
  { id: 'hundred-hits', label: '100 次命中', icon: '💯', unlocked: true },
  { id: 'multi-project', label: '跨 3 项目', icon: '🌍', unlocked: true },
  { id: 'no-conflicts', label: '零冲突', icon: '🏆', unlocked: false },
];

export const MOCK_STATS: MapStats = {
  total: 42,
  active: 35,
  conflicted: 1,
  other: 6,
  thisMonth: 7,
  growth: {
    level: 5,
    progress: 0.84,
    nextLevelAt: 50,
    achievements: ACHIEVEMENTS,
  } as GrowthData,
  byCategory: [
    { category: 'code', count: 12, active: 11, conflicted: 0 },
    { category: 'architecture', count: 8, active: 6, conflicted: 1 },
    { category: 'practice', count: 11, active: 10, conflicted: 0 },
  ],
};
